CREATE DATABASE QUANLITRUONGHOC;
USE QUANLITRUONGHOC;

-- TẠO BẢNG GV
CREATE TABLE GIAOVIEN(
ID_GIAO_VIEN INT PRIMARY KEY AUTO_INCREMENT,
TEN_GIAO_VIEN CHAR(255) NOT NULL
);

-- TẠO BẢNG HỌC SINH
CREATE TABLE HOCSINH(
ID_HOC_SINH INT PRIMARY KEY AUTO_INCREMENT,
TEN_HOC_SINH VARCHAR(255) NOT NULL,
ID_GV_CN INT ,
FOREIGN KEY (ID_GV_CN) REFERENCES GIAOVIEN(ID_GIAO_VIEN)
);

-- NHẬP DỮ LIỆU GIAOVIEN

INSERT INTO GIAOVIEN(ID_GIAO_VIEN,TEN_GIAO_VIEN) VALUES ('113','NGUYỄN THỊ GIÁO');
INSERT INTO GIAOVIEN(ID_GIAO_VIEN,TEN_GIAO_VIEN) VALUES ('115','TRẦN VĂN VIÊN');
INSERT INTO GIAOVIEN(ID_GIAO_VIEN,TEN_GIAO_VIEN) VALUES ('117','LÊ THỊ MƠ');

SELECT * FROM GIAOVIEN;


-- NHẬP DỮ LIỆU HỌC SINH

INSERT INTO HOCSINH (ID_HOC_SINH,TEN_HOC_SINH,ID_GV_CN) VALUES ('001','NGÔ VĂN HỌC','113');
INSERT INTO HOCSINH (ID_HOC_SINH,TEN_HOC_SINH,ID_GV_CN) VALUES ('002','NGUYỄN CÔNG SINH','115');
INSERT INTO HOCSINH (ID_HOC_SINH,TEN_HOC_SINH,ID_GV_CN) VALUES ('003','TRƯƠNG ĐÌNH HUY','117');

SELECT * FROM HOCSINH;