CREATE DATABASE QUANLITRUONGHOC;
USE QUANLITRUONGHOC;

-- TẠO BẢNG MANAGER
CREATE TABLE MANAGER(
ID_MANAGER INT PRIMARY KEY AUTO_INCREMENT,
NAME_MANAGER CHAR(255) NOT NULL,
DATE_MANAGER DATE
);

-- TẠO BẢNG TEAM

CREATE TABLE TEAM(
ID_TEAM INT PRIMARY KEY AUTO_INCREMENT,
NAME_TEAM CHAR(255) NOT NULL,
TEAM_ID INT ,
FOREIGN KEY (TEAM_ID) REFERENCES MANAGER(ID_MANAGER)
);

-- TẠO BẢNG PLAYER

CREATE TABLE PLAYER(
ID_PLAYER INT PRIMARY KEY AUTO_INCREMENT,
NAME_PLAYER CHAR(255) NOT NULL,
DATE_PLAYER DATE,
PLAYER_ID INT ,
FOREIGN KEY(PLAYER_ID) REFERENCES TEAM(ID_TEAM)
);

-- TẠO BẢNG LOCATION

CREATE TABLE LOCATION(
ID_LOCATION INT PRIMARY KEY AUTO_INCREMENT,
VI_TRI CHAR(255) NOT NULL
);


-- TẠO BẢNG MATCH
CREATE TABLE MATCHS (
ID_MATCHS INT PRIMARY KEY AUTO_INCREMENT,
NGAY_GIO_THI_DAU DATE,
DOI_A INT , 
DOI_B INT,
FOREIGN KEY (DOI_A) REFERENCES TEAM(ID_TEAM),
FOREIGN KEY (DOI_B) REFERENCES TEAM(ID_TEAM),
CHECK (DOI_A != DOI_B)
);

-- NHẬP THÔNG TIN MANAGER
INSERT INTO MANAGER (NAME_MANAGER, DATE_MANAGER) VALUES 
('Nguyen Van A', '1980-05-12'),
('Le Thi B', '1975-11-20');
SELECT * FROM MANAGER;

-- NHẬP THÔNG TIN TEAM
INSERT INTO TEAM (NAME_TEAM, TEAM_ID) VALUES 
('Team Alpha', 1),
('Team Beta', 2),
('Team Gamma', 1);
SELECT * FROM TEAM;

-- NHẬP THÔNG TIN PLAYER
INSERT INTO PLAYER (NAME_PLAYER, DATE_PLAYER, PLAYER_ID) VALUES 
('Tran Van C', '2000-01-01', 1),
('Nguyen Van D', '1999-02-15', 2),
('Le Thi E', '2001-07-10', 1),
('Pham Van F', '2002-03-25', 3);
SELECT * FROM PLAYER;

-- NHẬP THÔNG TIN LOCATION
INSERT INTO LOCATION (VI_TRI) VALUES 
('San A'),
('San B'),
('San C');
SELECT * FROM LOCATION;

-- NHẬP THÔNG TIN MATCHS;
INSERT INTO MATCHS (NGAY_GIO_THI_DAU, DOI_A, DOI_B) VALUES 
('2025-04-10', 1, 2),
('2025-04-12', 2, 3),
('2025-04-15', 3, 1);
SELECT * FROM MATCHS;